# Generated by Django 5.0.1 on 2024-01-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_rating',
            new_name='authorRating',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='userAuthor',
        ),
    ]
