# Generated by Django 5.0.1 on 2024-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_user_rating_author_authorrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_genre',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2),
        ),
    ]
