# Generated by Django 5.0.1 on 2024-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_genre',
            field=models.CharField(choices=[('article', 'article'), ('news', 'news')], max_length=32),
        ),
    ]
