# Generated by Django 5.0.1 on 2024-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_genre',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2),
        ),
    ]
