# Generated by Django 5.0.1 on 2024-02-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
